# Site settings
title: Fabienne Krotoff Ostéopathe
address: 8 rue Desnouettes Paris 15
tel: 01 45 31 98 48
email: fabienne.krotoff@gmail.com
description: >
  Cabinet ouvert du lundi au vendredi de 9h à 19h et le samedi de 9h à 13h<br>
  Diplômée du COE, DU de psychosomatique et de périnatalité

twitter_username: Osteo15
googleplus_username: 104301362970770277035
facebook_username: Osteo15

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://osteo15.com" # the base hostname & protocol for your site
permalink: pretty

# Build settings
markdown: kramdown
