# Site settings
title: Fabienne Krotoff Ostéopathe
address: 8 rue Desnouettes Paris 15
tel: 01 45 31 98 48
email: krotoffosteo@gmail.com
description: Cabinet d'ostéopathie de Fabienne Krotoff, Paris 15
lang: fr

twitter_username: osteopathe75015
facebook_username: KrotoffFabienneOsteopathe75015
googleplus_username: 104301362970770277035

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://osteo15.com" # the base hostname & protocol for your site
permalink: pretty

# Build settings
markdown: kramdown

exclude: [
  "vendor",
  "README.md",
  "Gemfile",
  "Gemfile.lock"
]

gems:
  - jekyll-sitemap
